In [4]:
import torch
import numpy as np

Es gibt 4 Methoden einen Tensor zu erzeugen

In [5]:
#1 aus daten
data = [[1,2,], [3,4,]]
torch.tensor(data)

tensor([[1, 2],
        [3, 4]])

In [8]:
#2 von Numpy
np_data = np.array([[1,2], [3,4]])
x = torch.from_numpy(np_data)
x

tensor([[1, 2],
        [3, 4]])

In [40]:
x.shape, x.dtype

(torch.Size([2, 2]), torch.int64)

In [41]:
torch.ones_like(x)

tensor([[1, 1],
        [1, 1]])

In [42]:
torch.rand_like(x, dtype=torch.float64) # ohne dtype geht es nicht, da x int ist

tensor([[0.9905, 0.9667],
        [0.0744, 0.8509]], dtype=torch.float64)

In [50]:
# 3 mit vordefinierten Befehlen
t = torch.rand(4,3)
t

tensor([[0.7089, 0.0024, 0.1426],
        [0.3587, 0.8520, 0.1917],
        [0.3403, 0.1736, 0.2067],
        [0.5201, 0.7291, 0.8412]])

In [51]:
t.size, t.dtype, t.device

(<function Tensor.size>, torch.float32, device(type='cpu'))

In [52]:
if torch.cuda.is_available():
    t = t.to("cuda")
t

tensor([[0.7089, 0.0024, 0.1426],
        [0.3587, 0.8520, 0.1917],
        [0.3403, 0.1736, 0.2067],
        [0.5201, 0.7291, 0.8412]])

In [53]:
# slicing
t[0]

tensor([0.7089, 0.0024, 0.1426])

In [54]:
t[1,1]

tensor(0.8520)

In [55]:
t[:,-1]

tensor([0.1426, 0.1917, 0.2067, 0.8412])

In [58]:
t[:,1]= 0.3
t

tensor([[0.7089, 0.3000, 0.1426],
        [0.3587, 0.3000, 0.1917],
        [0.3403, 0.3000, 0.2067],
        [0.5201, 0.3000, 0.8412]])

### MatMult

In [59]:
t.matmul(t.T)

tensor([[0.6129, 0.3716, 0.3607, 0.5787],
        [0.3716, 0.2554, 0.2517, 0.4378],
        [0.3607, 0.2517, 0.2485, 0.4409],
        [0.5787, 0.4378, 0.4409, 1.0682]])

In [62]:
# oder
torch.matmul(t, t.T)

tensor([[0.6129, 0.3716, 0.3607, 0.5787],
        [0.3716, 0.2554, 0.2517, 0.4378],
        [0.3607, 0.2517, 0.2485, 0.4409],
        [0.5787, 0.4378, 0.4409, 1.0682]])

In [61]:
# oder
t @ t.T

tensor([[0.6129, 0.3716, 0.3607, 0.5787],
        [0.3716, 0.2554, 0.2517, 0.4378],
        [0.3607, 0.2517, 0.2485, 0.4409],
        [0.5787, 0.4378, 0.4409, 1.0682]])

In [63]:
# aber 
t*t

tensor([[0.5025, 0.0900, 0.0203],
        [0.1286, 0.0900, 0.0367],
        [0.1158, 0.0900, 0.0427],
        [0.2705, 0.0900, 0.7077]])

In [64]:
t+t

tensor([[1.4178, 0.6000, 0.2853],
        [0.7174, 0.6000, 0.3833],
        [0.6807, 0.6000, 0.4133],
        [1.0402, 0.6000, 1.6824]])

In [65]:
t.sum()

tensor(4.5102)

In [67]:
# scalare können rausgeholt werden
t.sum().item()

4.510221481323242

In [68]:
# nicht permanent
t.add(8)

tensor([[8.7089, 8.3000, 8.1426],
        [8.3587, 8.3000, 8.1917],
        [8.3403, 8.3000, 8.2067],
        [8.5201, 8.3000, 8.8412]])

In [69]:
t

tensor([[0.7089, 0.3000, 0.1426],
        [0.3587, 0.3000, 0.1917],
        [0.3403, 0.3000, 0.2067],
        [0.5201, 0.3000, 0.8412]])

In [70]:
# permanent
t.add_(9)

tensor([[9.7089, 9.3000, 9.1426],
        [9.3587, 9.3000, 9.1917],
        [9.3403, 9.3000, 9.2067],
        [9.5201, 9.3000, 9.8412]])

In [71]:
t

tensor([[9.7089, 9.3000, 9.1426],
        [9.3587, 9.3000, 9.1917],
        [9.3403, 9.3000, 9.2067],
        [9.5201, 9.3000, 9.8412]])

In [72]:
## numpy und torch können speicher teilen
t = torch.rand(3,4)
n = t.numpy()
n

array([[0.4928438 , 0.30978137, 0.10848749, 0.5321654 ],
       [0.40828836, 0.81738263, 0.39298618, 0.2529902 ],
       [0.02767897, 0.87981504, 0.3863513 , 0.39219964]], dtype=float32)

In [73]:
t.add_(2)
n

array([[2.4928439, 2.3097813, 2.1084876, 2.5321655],
       [2.4082885, 2.8173826, 2.3929863, 2.2529902],
       [2.027679 , 2.879815 , 2.3863513, 2.3921995]], dtype=float32)

In [82]:
#geht auch andersrum
n = np.ones((4,4))
t = torch.from_numpy(n)
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [83]:
np.add(n, 2, out=n)
t

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]], dtype=torch.float64)